[package]
name="racemus_client"
version="0.1.0"
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/codedjinn/amethyst", branch = "master" }

[features]
default = ["vulkan"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
